### ISSUE TITLE
Enhancement: File transfer

### ISSUE THREAD

**Issue by pykong** [fabrixxm/SendToPhoneDestkop#1]
Thanks for putting up this neat little Sailfish app!

I'd like to have the option to transfer files to my phone. Send small configuration files like an openvpn config over to my phone would suffice my own requirements.

Just a wish of an avid user...

**Comment by fabrixxm** [comment]
Hi @pykong 
I think you should ask to Send To Phone app developer here; https://github.com/mkiol/SendToJolla
This was just an experiment to build a desktop app to interact with it.
I'm not developing this anymore, sorry :)

**Comment by pykong** [comment]
@fabrixxm The github search led me astray. Thanks for pointing me out the right repo.
